### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by voa18105** [barisgecer/facegan#1]
Dear Baris, thank you for your codes! Do you mind helping me a bit to launch it? I am stuck with attempt not to train it, but to use your model. It asks me why '--dataset' is empty... but why shouldn't it be if I am not training the model, but willing only to synthesis some new faces?

**Comment by barisgecer** [comment]
Hi, 
I haven't put pretrained model yet. I can put it later of there is more interest. But for the moment, you can train it from scratch with number of datasets as described in the paper and in the readme file. Please let me now how it goes.

**Comment by barisgecer** [comment]
all_all_all_scaled.mat file is included LSFM model
https://xip.uclb.com/i/healthcare_tools/LSFM.html. You need to apply for license to use it. Alternatively you can use basel face model.

**Comment by voa18105** [comment]
Ok, I see, thank you! I am working on launching it :-)

**Comment by Sayyam-Jain** [comment]
> Dear Baris, thank you for your codes! Do you mind helping me a bit to launch it? I am stuck with attempt not to train it, but to use your model. It asks me why '--dataset' is empty... but why shouldn't it be if I am not training the model, but willing only to synthesis some new faces?


Can you please tell me the steps to generate new faces from the given pretrained model?
Thanks

**Comment by huxianer** [comment]
@voa18105 @barisgecer Hi,Thanks for your work,I can not find all_all_all_scaled.mat ,Could you give me any help,THKS!

**Comment by huxianer** [comment]
@voa18105 Could you share all_all_all_scaled.mat  with me,Thank you very much!

**Comment by barisgecer** [comment]
> all_all_all_scaled.mat file is included LSFM model
> https://xip.uclb.com/i/healthcare_tools/LSFM.html. You need to apply for license to use it. Alternatively you can use basel face model.

The all_all_all_scaled.mat is LSFM model which is under license. You need to apply for the license at the above link.

**Comment by barisgecer** [comment]
> > Dear Baris, thank you for your codes! Do you mind helping me a bit to launch it? I am stuck with attempt not to train it, but to use your model. It asks me why '--dataset' is empty... but why shouldn't it be if I am not training the model, but willing only to synthesis some new faces?
> 
> Can you please tell me the steps to generate new faces from the given pretrained model?
> Thanks

That is explained here  https://github.com/barisgecer/facegan#usage
