### ISSUE TITLE
How Can I generate tranining data?

### ISSUE THREAD

**Issue by xiaoxingzeng** [barisgecer/facegan#4]
The gen_syn_latent.m  lack of render_face function in your files.

**Comment by barisgecer** [comment]
You may find many helper functions I used here : http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm

You may find that particular file attached.
[render_face.m.zip](https://github.com/barisgecer/facegan/files/2691717/render_face.m.zip)

**Comment by xiaoxingzeng** [comment]
thanks, Baris
