### ISSUE TITLE
Can you please explain the steps to generate faces from given pretrained model? 

### ISSUE THREAD

**Issue by Sayyam-Jain** [barisgecer/facegan#5]

**Comment by jiyuay** [comment]
@Sayyam-Jain hi! could you tell me which system you run the code, Windows or Linux? Thank you so much!

**Comment by barisgecer** [comment]
@Sayyam-Jain did you manage to generate them?

**Comment by ghost** [comment]
@barisgecer the test script is also used for inference for the pretrained model?
