### ISSUE TITLE
windows or linux?

### ISSUE THREAD

**Issue by jiyuay** [barisgecer/facegan#6]
when i see the environment.yml, it seems that it should be run in windows. but in the readme file, the symbol $ indicate it is run in linix, which system should i should the code? Thank you so much!

**Comment by jiyuay** [comment]
@barisgecer

**Comment by barisgecer** [comment]
Hi, yes yml file is generated on Windows, but I was running the code on both Linux and Windows machines. There might be small modifications on yml file but it shouldn't be very difficult set up the environment on Linux thanks to conda. Hope this helps.
