### ISSUE TITLE
The question about 300W-3D database generate tranining data  

### ISSUE THREAD

**Issue by Gincoeng** [barisgecer/facegan#8]
According to the readme.txt in 3DDFA , I can't  generated the training data with the MATLAB code.  Except the testing picture in the original folder. When add the *.mat from "300W-3D" and *_face.mat from"300W-3D-Face" to the 'input/' folder , just come out the all black picture.  Can  you give me some idea ? Thank you very much.

**Comment by barisgecer** [comment]
Could it be because type problem (int vs float or range of 0-1 vs 0-255)? Worst case scenario it might be rendering out of camera perspective.

**Comment by Gincoeng** [comment]
I apologize for replying late，  I will try it .Thank you so much
